projects:
  shiftlinkmain:
    schemaPath: graphql/schema.json
    includes:
      - graphql/**/*.graphql
    excludes:
      - ./amplify/**
    extensions:
      amplify:
        codeGenTarget: swift
        generatedFileName: ShiftlinkMain/Services/API.swift
        docsFilePath: graphql
extensions:
  amplify:
    version: 3
